#!/bin/sh

PINFILE=~/.pinned

sedescape() {
	echo $1 | sed -r 's/([\$\.\*\/\[\\^])/\\\1/g' | sed 's/[]]/\[]]/g'
}

verintgrty() {
	fcksum=$(sha1sum $1 | awk '{print $1}')
	bcksum=$(sha1sum $2 | awk '{print $1}')

	if [ $fcksum != $bcksum ];then
		echo Backup failed. >&2
		exit 2
	fi
}

while getopts :s:d:neb opt
do
	case $opt in
	s)
		head -$OPTARG $PINFILE | tail -1 | cut -d';' -f1
	;;
	d)
		url=$(sedescape `head -$OPTARG $PINFILE | tail -1 | cut -d';' -f1`)
		sed -i "/^$url;.*/d" $PINFILE
	;;
	n) wc -l $PINFILE | cut -d' ' -f1
	;;
	e) $EDITOR $PINFILE
	;;
	b)
		cp $PINFILE $PINFILE.bk
		verintgrty $PINFILE $PINFILE.bk
		echo Done.
	;;
	:)
		if [ $OPTARG = s ];then
			cut -d';' -f2 $PINFILE | cat -n
		else
			echo $OPTARG requires an argument. >&2
			exit 3
		fi
	;;
	esac
done
shift $(($OPTIND - 1))

if [ ! -z "$1" ];then
	if [ -z "$2" ];then
		echo "${1};No Description" | tr -d '\n' | sed 'a\' >> $PINFILE
	else
		echo "${1};$2" | tr -d '\n' | sed 'a\' >> $PINFILE
	fi
else
	exit 1
fi

